# General
server:
  port: 8080
  error:
    whitelabel.enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
